### ISSUE TITLE
[2019.09.26] 성준영 선배님

### ISSUE THREAD

**Issue by ghost** [TG-WinG/Tech-Concert#1]
### Profile
- Naver corp.
- 스토리지 & 클라우드 플랫폼  
- 분산스토리지 플랫폼  
- **@sungjunyoung**

### Tech Concert
- 수업은 OS, OSS, 알고리즘, 자구 등 근본 위주로 열심히 해주세요
- 언어는 중요하지 않다
- 하나의 프레임워크만 파기보다는 구덩이는 넓게 파야한다
- 책만 보지 말고 자기가 무엇인가 만들어보면서 해라
- 우분투 안써도 됨니다.. GUI 위주가 아닌 CLI 위주로 OS 를 써보는 것도.. (homebrew 등)
- 맥북으로 리눅스 커맨드를 많이 연습해라
- 반복되는 작업을 최소화시키기 위해 스크립트를 만들어서 자동화 시켜보아라
- 슬랙 뿐만 아니라 API 를 지원하는 여러 소프트웨어들을 엮어서 할수 있는 것들을 해보기
- 크롬 on -> cgv -> 좌석 있나 확인 -> ... 이런거 자동화 예시
- 해커톤 / 공모전 나가라. 못 하더라도 나가라. 팀 사람이 알려준 것으로 다른데 나가서 써먹기
- 블로그 만들어라 -> 깃헙 페이지 등으로 만들면서 html, js, css 등등 같이 코드보기
- 인스타는 인맥관리용, 페이스북, 트위터 등에서 개발 정보 찾아라
- 노드 꼭써라  오픈소스 많다 & NO 써보기 (작은 오픈소스에 컨트리뷰션 해보기)
- CLI 프로그래밍을 해보면 배울게 많음

**Comment by sungjunyoung** [comment]
https://github.com/T-G-WinG/2019-2-Networking/issues/1#issuecomment-538859226

고쳐주세요,,

**Comment by ghost** [comment]
> [T-G-WinG/2019-2-Networking#1 (comment)](https://github.com/T-G-WinG/2019-2-Networking/issues/1#issuecomment-538859226)
> 
> 고쳐주세요,,

제가 밑에 내용을 못봤네용 ㅠ.ㅠ
고쳤습니다 행님 😂

**@sungjunyoung**
