### ISSUE TITLE
[2021.03.13] 이근철 선배님

### ISSUE THREAD

**Issue by ghost** [TG-WinG/Tech-Concert#4]
### Profile
- [Naver Webtoon Corp Global Webtoon Tech](https://www.webtoons.com)
- 서버 개발자 겸 플랫폼 개발자
  - Global Webtoon 소소한 서비스 이슈 처리
  - 비동기 처리를 통한 대용량 App push 개발
- Spingboot, Apache Kafka, Redis, Mysql, Cassandra

**Comment by LeeKeunCheol** [comment]
## 누구세요?
- 11학번 이근철
- 네이버 웹툰 서버 개발자

## 무엇을 해왔나
- 네이버 포스트 팀으로 입사
  - 유지보수 및 각종 피쳐 개발
  - spring 4, apache, tomcat, jsp, jQuery

- 글로벌 ugc 플랫폼 팀으로 이동
  - 배포 프로세스 구성 및 피쳐 개발
  - spring boot 1.x, spring cloud
  - 팀 터짐 (ㅠㅠ)

- 클로바 뮤직 팀으로 이동
  - 뮤직 플랫폼 개발 (python -> java)
  - spring boot 1.x, docker

- 글로벌 웹툰 팀으로 이동
  - 대용량 푸시 플랫폼 개발
  - spring boot 2.x, spring reactor, docker, vue js


## 컴퓨터공학과가 졸업해서 할수 있는일?
- 앱 개발자 (ios / aos)
- fe 개발자
- 서버개발자
- 빅데이터 개발자
- ai 개발자
- 임베디드 개발자

## 서버 개발자를 선택하게 된 이유
- 최초 필기 시험은 fe 개발자로 합격했었다.
- 면접 도중, 궁금한것 없냐는 질문에 혹시 합격하게 된다면 서버 개발자 쪽으로 갈수는 없는지 문의 했었음.
- 그냥 재밌어 보여서

## 서버개발자의 장 단점
- 장점
  - 다른 개발직군에 비해 경험해볼수 있는 기술이 많다.
    - 주로 중요 데이터는 서버쪽에서 처리하기 때문

- 단점
  - 앱의 문제로 장애가 나더라도 서버 개발자가 수정해야한다. (급작스런 야근 가능성이 있다......)

## 취업준비 썰
- 안했다
- 지원 불가 (영어점수 없음) : 삼성, 현대
- 지원 안함 : cj
- 각종 대기업 광탈 : sk, kt, lg 등등...
- 최종합격 : 티맥스 소프트, 네이버 / 서류통과 : nhn, 쿠팡
- 합격했는데 영어점수 없어서 졸업 못할뻔함 ㅋㅋㅋㅋㅋ

## 취업 준비를 어떻게 해야할까요??
- 알고리즘 준비느 그냥 필수
- 뭐든 많이 해보면 면접때 할 이야기가 많아서 좋다.

- 그냥 아무거나 상관없이 돈벌고 싶다 (문화 상관 없음)
  - 대기업 준비
  - 돈은 요새 it가 더줌

- it 회사는 가고싶은데 (개발자로 살고싶은데) 어떤걸 준비할지 모르겠다
  - 그러면 그냥 java 에 springboot 띄워서 이것저것 가지고 놀아라
  - 우리회사에 서버개발자 없어요

- 앱 개발자 (ios / aos) 가 되고 싶다
  - kotlin / swift 로 앱 개발해보기

- fe 개발자 가 되고 싶다
  - fe 프레임워크를 선택하여 개발 진행 해보기 (보통 서버랑 병행)

- 서버개발자 가 되고 싶다
  - java, spring (한국은 자바공화국)
  -  (보통 fe랑 병행)

- 빅데이터 개발자 가 되고 싶다
  - hadoop, spark, kafak streaming
 
- ai 개발자 가 되고 싶다
  - 대학원 가야함
